
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { UserProfile, TestResult, Goal, Roadmap, StudyStats, Note, Achievement } from '../types';

interface PortfolioSettings {
  template: 'minimal' | 'technical' | 'creative' | 'academic' | 'custom';
  primaryColor: string;
  showStats: boolean;
  showRoadmaps: boolean;
  customTemplate?: string;
  customCss?: string;
}

interface Account extends UserProfile {
  id: string;
  email: string;
  password?: string;
}

interface StoreContextType {
  user: Account | null;
  login: (email: string, pass: string) => boolean;
  signup: (details: Omit<Account, 'id' | 'hasTakenTest'>) => void;
  logout: () => void;
  testResult: TestResult | null;
  setTestResult: (result: TestResult) => void;
  goals: Goal[];
  addGoal: (text: string, type: 'daily' | 'weekly') => void;
  toggleGoal: (id: string) => void;
  deleteGoal: (id: string) => void;
  roadmaps: Roadmap[];
  saveRoadmap: (roadmap: Roadmap) => void;
  deleteRoadmap: (id: string) => void;
  toggleRoadmapTopic: (roadmapId: string, phaseIndex: number, topicIndex: number) => void;
  studyStats: StudyStats;
  updateStats: (updates: Partial<StudyStats>) => void;
  notes: Note[];
  addNote: (title: string, content: string) => void;
  deleteNote: (id: string) => void;
  achievements: Achievement[];
  addAchievement: (ach: Omit<Achievement, 'id' | 'unlockedAt'>) => void;
  unlockAchievement: (achievement: Omit<Achievement, 'unlockedAt'>) => void;
  updateAchievement: (id: string, updates: Partial<Achievement>) => void;
  deleteAchievement: (id: string) => void;
  portfolioSettings: PortfolioSettings;
  updatePortfolioSettings: (settings: Partial<PortfolioSettings>) => void;
  resetData: () => void;
}

const StoreContext = createContext<StoreContextType | undefined>(undefined);

const INITIAL_STATS: StudyStats = {
  studyHours: 0,
  problemsSolved: 0,
  codingHours: 0,
  streak: 0,
  lastActive: Date.now(),
};

const DEFAULT_CUSTOM_HTML = `
<div class="custom-portfolio">
  <h1>{{name}}</h1>
  <p class="subtitle">{{grade}} Student - {{year}}</p>
  
  <div class="stats-grid">
    <div class="stat-card">
      <h3>Study Hours</h3>
      <p>{{stats_hours}}h</p>
    </div>
    <div class="stat-card">
      <h3>Problems</h3>
      <p>{{stats_problems}}</p>
    </div>
  </div>

  <h2>Skills & Expertise</h2>
  <div class="skills-tags">{{skills}}</div>

  <h2>Key Achievements</h2>
  <div class="achievements-section">
    {{achievements_html}}
  </div>

  <footer>
    Generated by StudentPath AI • {{email}}
  </footer>
</div>
`.trim();

const DEFAULT_CUSTOM_CSS = `
.custom-portfolio {
  color: #1a202c;
  line-height: 1.6;
}
.custom-portfolio h1 {
  font-size: 3rem;
  font-weight: 900;
  margin-bottom: 0.5rem;
  color: #4f46e5;
}
.subtitle {
  font-size: 1.25rem;
  color: #718096;
  margin-bottom: 2rem;
}
.stats-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
  margin-bottom: 2rem;
}
.stat-card {
  background: #f7fafc;
  padding: 1.5rem;
  border-radius: 1rem;
  text-align: center;
}
.stat-card h3 {
  font-size: 0.75rem;
  text-transform: uppercase;
  color: #a0aec0;
}
.stat-card p {
  font-size: 2rem;
  font-weight: 800;
}
.skills-tags {
  background: #ebf4ff;
  padding: 1rem;
  border-radius: 0.5rem;
  color: #2b6cb0;
  font-weight: 600;
  margin-bottom: 2rem;
}
.achievements-section {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}
.achievement-item {
  border-left: 4px solid #4f46e5;
  padding-left: 1rem;
  margin-bottom: 1rem;
}
.achievement-item h4 {
  font-weight: 800;
  font-size: 1.1rem;
}
footer {
  margin-top: 3rem;
  text-align: center;
  font-size: 0.8rem;
  color: #cbd5e0;
}
`.trim();

const INITIAL_PORTFOLIO: PortfolioSettings = {
  template: 'technical',
  primaryColor: '#4f46e5',
  showStats: true,
  showRoadmaps: true,
  customTemplate: DEFAULT_CUSTOM_HTML,
  customCss: DEFAULT_CUSTOM_CSS
};

export const StoreProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<Account | null>(() => {
    const active = localStorage.getItem('sp_active_user');
    return active ? JSON.parse(active) : null;
  });

  const [accounts, setAccounts] = useState<Account[]>(() => {
    const saved = localStorage.getItem('sp_accounts');
    return saved ? JSON.parse(saved) : [];
  });

  const [testResult, setTestResultState] = useState<TestResult | null>(null);
  const [goals, setGoalsState] = useState<Goal[]>([]);
  const [roadmaps, setRoadmapsState] = useState<Roadmap[]>([]);
  const [studyStats, setStudyStats] = useState<StudyStats>(INITIAL_STATS);
  const [notes, setNotes] = useState<Note[]>([]);
  const [achievements, setAchievements] = useState<Achievement[]>([]);
  const [portfolioSettings, setPortfolioSettings] = useState<PortfolioSettings>(INITIAL_PORTFOLIO);

  useEffect(() => {
    if (user) {
      const prefix = `sp_data_${user.id}_`;
      setTestResultState(JSON.parse(localStorage.getItem(prefix + 'testResult') || 'null'));
      setGoalsState(JSON.parse(localStorage.getItem(prefix + 'goals') || '[]'));
      setRoadmapsState(JSON.parse(localStorage.getItem(prefix + 'roadmaps') || '[]'));
      setStudyStats(JSON.parse(localStorage.getItem(prefix + 'stats') || JSON.stringify(INITIAL_STATS)));
      setNotes(JSON.parse(localStorage.getItem(prefix + 'notes') || '[]'));
      setAchievements(JSON.parse(localStorage.getItem(prefix + 'achievements') || '[]'));
      setPortfolioSettings(JSON.parse(localStorage.getItem(prefix + 'portfolio') || JSON.stringify(INITIAL_PORTFOLIO)));
      localStorage.setItem('sp_active_user', JSON.stringify(user));
    } else {
      localStorage.removeItem('sp_active_user');
    }
  }, [user]);

  useEffect(() => {
    if (user) {
      const prefix = `sp_data_${user.id}_`;
      localStorage.setItem(prefix + 'testResult', JSON.stringify(testResult));
      localStorage.setItem(prefix + 'goals', JSON.stringify(goals));
      localStorage.setItem(prefix + 'roadmaps', JSON.stringify(roadmaps));
      localStorage.setItem(prefix + 'stats', JSON.stringify(studyStats));
      localStorage.setItem(prefix + 'notes', JSON.stringify(notes));
      localStorage.setItem(prefix + 'achievements', JSON.stringify(achievements));
      localStorage.setItem(prefix + 'portfolio', JSON.stringify(portfolioSettings));
    }
  }, [testResult, goals, roadmaps, studyStats, notes, achievements, portfolioSettings, user]);

  useEffect(() => {
    localStorage.setItem('sp_accounts', JSON.stringify(accounts));
  }, [accounts]);

  const login = (email: string, pass: string) => {
    const found = accounts.find(a => a.email === email && a.password === pass);
    if (found) {
      setUser(found);
      return true;
    }
    return false;
  };

  const signup = (details: Omit<Account, 'id' | 'hasTakenTest'>) => {
    const newAccount: Account = {
      ...details,
      id: crypto.randomUUID(),
      hasTakenTest: false
    };
    setAccounts(prev => [...prev, newAccount]);
    setUser(newAccount);
  };

  const logout = () => {
    setUser(null);
  };

  const updatePortfolioSettings = (settings: Partial<PortfolioSettings>) => {
    setPortfolioSettings(prev => ({ ...prev, ...settings }));
  };

  const setTestResult = (r: TestResult) => {
    setTestResultState(r);
    if (user) {
      const updatedUser = { ...user, hasTakenTest: true };
      setUser(updatedUser);
      setAccounts(prev => prev.map(a => a.id === user.id ? updatedUser : a));
    }
  };

  const addGoal = (text: string, type: 'daily' | 'weekly') => {
    const newGoal: Goal = {
      id: crypto.randomUUID(),
      text,
      completed: false,
      type,
      createdAt: Date.now(),
    };
    setGoalsState(prev => [newGoal, ...prev]);
  };

  const toggleGoal = (id: string) => {
    setGoalsState(prev => prev.map(g => g.id === id ? { ...g, completed: !g.completed } : g));
  };

  const deleteGoal = (id: string) => {
    setGoalsState(prev => prev.filter(g => g.id !== id));
  };

  const saveRoadmap = (roadmap: Roadmap) => {
    if (roadmaps.find(r => r.domain === roadmap.domain)) return;
    setRoadmapsState(prev => [roadmap, ...prev]);
  };

  const deleteRoadmap = (id: string) => {
    setRoadmapsState(prev => prev.filter(r => r.id !== id));
  };

  const toggleRoadmapTopic = (roadmapId: string, phaseIndex: number, topicIndex: number) => {
    setRoadmapsState(prev => prev.map(roadmap => {
      if (roadmap.id !== roadmapId) return roadmap;
      const newPhases = roadmap.phases.map((phase, pIdx) => {
        if (pIdx !== phaseIndex) return phase;
        const newTopics = phase.topics.map((topic, tIdx) => {
          if (tIdx !== topicIndex) return topic;
          return { ...topic, completed: !topic.completed };
        });
        return { ...phase, topics: newTopics };
      });
      return { ...roadmap, phases: newPhases };
    }));
  };

  const updateStats = (updates: Partial<StudyStats>) => {
    setStudyStats(prev => ({ ...prev, ...updates, lastActive: Date.now() }));
  };

  const addNote = (title: string, content: string) => {
    const newNote: Note = {
      id: crypto.randomUUID(),
      title,
      content,
      createdAt: Date.now(),
    };
    setNotes(prev => [newNote, ...prev]);
  };

  const deleteNote = (id: string) => {
    setNotes(prev => prev.filter(n => n.id !== id));
  };

  const updateAchievement = (id: string, updates: Partial<Achievement>) => {
    setAchievements(prev => prev.map(a => a.id === id ? { ...a, ...updates } : a));
  };

  const unlockAchievement = (ach: Omit<Achievement, 'unlockedAt'>) => {
    if (achievements.find(a => a.id === ach.id)) return;
    setAchievements(prev => [{ ...ach, unlockedAt: Date.now() }, ...prev]);
  };

  const addAchievement = (ach: Omit<Achievement, 'id' | 'unlockedAt'>) => {
    const newAch: Achievement = {
        ...ach,
        id: crypto.randomUUID(),
        unlockedAt: Date.now()
    };
    setAchievements(prev => [newAch, ...prev]);
  };

  const deleteAchievement = (id: string) => {
    setAchievements(prev => prev.filter(a => a.id !== id));
  };

  const resetData = () => {
    if (user) {
      const prefix = `sp_data_${user.id}_`;
      localStorage.removeItem(prefix + 'testResult');
      localStorage.removeItem(prefix + 'goals');
      localStorage.removeItem(prefix + 'roadmaps');
      localStorage.removeItem(prefix + 'stats');
      localStorage.removeItem(prefix + 'notes');
      localStorage.removeItem(prefix + 'achievements');
      localStorage.removeItem(prefix + 'portfolio');
      setTestResultState(null);
      setGoalsState([]);
      setRoadmapsState([]);
      setStudyStats(INITIAL_STATS);
      setNotes([]);
      setAchievements([]);
      setPortfolioSettings(INITIAL_PORTFOLIO);
    }
  };

  return (
    <StoreContext.Provider value={{
      user, login, signup, logout,
      testResult, setTestResult,
      goals, addGoal, toggleGoal, deleteGoal,
      roadmaps, saveRoadmap, deleteRoadmap, toggleRoadmapTopic,
      studyStats, updateStats,
      notes, addNote, deleteNote,
      achievements, unlockAchievement, addAchievement, updateAchievement, deleteAchievement,
      portfolioSettings, updatePortfolioSettings,
      resetData
    }}>
      {children}
    </StoreContext.Provider>
  );
};

export const useStore = () => {
  const context = useContext(StoreContext);
  if (!context) throw new Error("useStore must be used within a StoreProvider");
  return context;
};
